version: '3.9'

services:
  open-webui:
    build:
      # Use the 'open-webui' folder as the source for the build.
      context: ./open-webui
      # Specify our new production Dockerfile.
      dockerfile: Dockerfile.prod
    ports:
      # Connect port 8080 on your VPS to port 8080 inside the container.
      - "8080:8080"
    environment:
      # Tell the backend where to find your LiteLLM service.
      - LITELLM_API_URL=http://litellm:4000
    networks:
      # Connect this container to the network used by LiteLLM.
      - litellm_network
    restart: unless-stopped

networks:
  litellm_network:
    # Tell Docker this network is created externally.
    name: litellm_network
    external: true


