version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    build:
      context: ./open-webui
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_BASE_URL=/api/v1
    depends_on:
      - backend
    restart: on-failure

  backend:
    build:
      context: ./open-webui
      dockerfile: ./backend/Dockerfile
    environment:
      - LITELLM_API_URL=http://litellm:4000
    volumes:
      - ./open-webui/backend:/app
    depends_on:
      - litellm
    restart: on-failure

networks:
  litellm_network:
    name: litellm_network
    external: true


