general_settings:
  master_key: "sk-12345"
  salt_key: "sk-12345"
  database_url: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
  # highlight-start
  # This section enables the Admin UI for the specified email addresses
  admin_users:
    - "your.email@example.com"
    - "another.admin@example.com"
  # highlight-end

# You can keep the model list empty, as you'll add models through the UI
model_list: []